### PR TITLE
Update copyright statement

### LINKED ISSUE #1: Fix copyright notice
It seems that large parts of this were copied from the pandoc/lua-filters repo. I'm actually quite happy to see this happening, but please credit the original author (@b3), as required by the license.

### PR DESCRIPTION
**Pull request by tarleb**
Include the original author in the copyright line.

Closes: #1

### CODE REVIEW

**Review by SamEdwardes — APPROVED** [review]

**Comment by SamEdwardes** [comment]
Thank you @tarleb. I have never "vendored" code before, so I was unsure what the appropriate approach was. I gave credits in the README:

https://github.com/SamEdwardes/include-code-files/blob/e15e26d43ec15fc744242b6dd6565cdacf0205e5/README.md?plain=1#L7

Thank you for correcting the credits in the license!

I am also going to update the copyright in the code.

**Comment by tarleb** [comment]
Awesome, thank you!

If it's ok for you (and for @b3), then I'd like to add a link to the readme in pandoc/lua-filters and declare this the "official" repository for this filter. I want to successively move all filters into dedicated repos and would be happy to turn the maintainership over to you (but you can always ping me in case of questions).

**Comment by SamEdwardes** [comment]
I am happy to do this. We can wait for @b3 to confirm. They are the original author of the actual code, so it could make sense to live under their account.

**Comment by b3** [comment]
I did not follow seriously enough the results of pandoc/lua-filters#207 reflexions nor the differences between code here and the one stored in the original [include-code-files](https://github.com/pandoc/lua-filters/tree/master/include-code-files).

For this last part and for what I have seen, it seems there are no differences in the lua code but pretty much in the repository structure. I guess that's done in order to be adapted to Quarto conventions and needs.

I thus frankly do not know what to answer for now.

I'd like to adapt the filter to the decisions coming from pandoc/lua-filters#207, which certainly means to have a dedicated repo for it somewhere (as @tarleb said), but I really want it to be done in a way the repo is understood as a **pandoc** extension and not as an extension dedicated to some tools coming from or using pandoc (being Quarto or anything else) with simple documentation for people wanting to use with pandoc, as well as with clean tests.

I was ready to create a dedicated repo for it but was not sure how to do it properly. I was waiting for someone to propose a template for such repos ;-)

I fear that using this one may hide the fact that code is firstly an extension for pandoc (i.e. usable by *simple* pandoc users).

I am not sure if I am my explanations are very clear.

Do not hesitate to correct me if needed.

**Comment by b3** [comment]
OK I am dumb (or at least lack attention).

@tarleb created such a template almost a year ago (https://github.com/pandoc/lua-filters/issues/207#issuecomment-1022128531).

I will try to set up such a repo for the filter.

**Comment by b3** [comment]
Just to try @tarleb template I created a repo for the filter here: https://github.com/b3/include-code-files.

What both of you think of it?

**Comment by b3** [comment]
Just in case my repo is not good enough for Quarto integration (I do not know anything about Quarto) I have prepared a modification of this in https://github.com/SamEdwardes/include-code-files/pull/4.

**Comment by tarleb** [comment]
Both options LGTM! I think the new repo would just need a release to make it usable with Quarto. Running `git push --tags` is probably enough -- I forgot to add that to the template. With the new repo we'd still need to bring Sam's changes to the README over.

My suggestion would be to use the new repo and to add @SamEdwardes as collaborator. Multiple maintainers are, in my experience, the most effective way to keep a project running and healthy, and Sam can do things that are specific to Quarto.

BTW, improvement ideas for my template are always welcome.

**Comment by SamEdwardes** [comment]
Thanks, @b3 and @tarleb. I will do some investigation. The purpose of my creating this repo was so that I could use `include-code-files` with Quarto. I will:

- Check to see if I can get Quarto to use <https://github.com/b3/include-code-files>.
- If not, I can look into setting up this repo to pull from <https://github.com/b3/include-code-files>.
- If that does not work, it may need its dedicated quarto repo, and the two different repos may diverge over time.

What do you think?

**Comment by b3** [comment]
@tarleb I did the `git push --tags` that I forgot to do. I already included Sam's changes in the second proposition (https://github.com/SamEdwardes/include-code-files/pull/4 which comes from a branche from my fork of Sam's repo : https://github.com/b3/fork-include-code-files/tree/introduce-pure-pandoc-support), it thus should be easy to put them in the README.

@SamEdwardes OK with that even if I think we should try to avoid divergence if the main goal of the code is the same. I added you and @tarleb as collaborator so that it may be more easy to investigate and because I agree with @tarleb that multiple maintainers may be more effective. 

@tarleb Do you think it could be a good idea to move the repo under https://github.com/pandoc-ext/ namespace?

**Comment by tarleb** [comment]
:+1: I tested it and can confirm that it's now possible to install the filter as a quarto extension by running

``` bash
$ quarto install extension b3/include-code-files
```

> Do you think it could be a good idea to move the repo under https://github.com/pandoc-ext/ namespace?

I'd be ok with that, but I also really like the idea of having things more decentralized. Your call. Adding the `pandoc-filter` and `quarto-extension` topics to the repo will make it easy to discover either way. To transfer it, you'd have to transfer it to me first, so that I can then transfer it to the pandoc-ext.

**Comment by b3** [comment]
> I'd be ok with that, but I also really like the idea of having things more decentralized. Your call. 
> Adding the `pandoc-filter` and `quarto-extension` topics to the repo will make it easy to discover either way.

I like things to be decentralized too (that's the whole of git after all), but I also like to simplify the search of pandoc filters. I guess that adding links repos into https://github.com/pandoc/lua-filters/blob/master/README.md and using topics may be sufficient.

Since I do not use github a lot these days (but differents gitlab instances such as the one of my [University](https://gitlab.univ-lille.fr/b3)) and since I guess you have more experience than me in this pandoc area I let you decide what is the best solution.

**Comment by tarleb** [comment]
Then let us leave it decentralized for now.

**Comment by b3** [comment]
Fine for me.

**Comment by b3** [comment]
@SamEdwardes I set up a branch of my repo (called [quarto](https://github.com/b3/include-code-files/tree/quarto)) with modifications taken from yours so that you can check if it is OK with you. If it is the case we can merge it with the `main` branch.

The only I did not put in it was the `justfile` since I do not know if is something needed by quarto or a target that we should to add in the `Makefile`.

**Comment by SamEdwardes** [comment]
Hi @b3, apologies this is on my to-do list still!

**Comment by SamEdwardes** [comment]
Hi @b3 and @tarleb - apologies for the delay on this. I confirmed that I am able to get everything working using b3/include-code-files!

```bash
quarto install extension b3/include-code-files
```

I would like to propose a few changes to the README which I will handle in a PR on the b3/include-code-files repo.

Lastly, I will archive this repo to avoid people finding duplicate solutions.

Thanks for the great work :)

**Pull request merged**
